apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::571138215324:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DA8993XCEBDQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::571138215324:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-25T22:46:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1589"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 813ba955-9ed9-11ea-8b6b-02da5a976b2c
