apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::571138215324:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7OFPASJPDRUJ
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      rolearn: arn:aws:iam::571138215324:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-24T05:55:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "13490"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2886f089-9d83-11ea-8f83-0a0cd58f4b92
